name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: cd client_go && go build && GOOS=windows go build -o main.exe
      
    - name: Upload the Build Artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Client binarys
        path: client_go/main*
